site_name: Axion Simulator
site_description: High-performance differentiable physics simulator for robotics and machine learning
repo_url: https://github.com/aleskucera/axion.git
repo_name: aleskucera/axion

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - First Simulation: getting-started/first-simulation.md
  - User Guide:
    - Basic Concepts: user-guide/concepts.md
    - Configuration System: user-guide/configuration.md
    - Logging & Analysis: user-guide/logging.md
  - API Reference:
    - Core Engine: api/engine.md
    - Constraints: api/constraints.md
  - Advanced Topics:
    - Performance Tuning: advanced/performance.md
    - GPU Optimization: advanced/gpu.md
    - Differentiable Physics: advanced/differentiable.md
  - Developer Guide:
    - Architecture: developer/architecture.md
    - Contributing: developer/contributing.md
    - Testing: developer/testing.md

plugins:
  - search
  
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: red
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
