site_name: Axion Simulator
site_url: https://sitename.example
theme:
  name: material
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: red
      accent: deep orange
    
