site_name: Axion Simulator
site_description: High-performance differentiable physics simulator for robotics and machine learning
repo_url: https://github.com/aleskucera/axion.git
repo_name: aleskucera/axion

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - First Simulation: getting-started/first-simulation.md
    - Configuration System: getting-started/configuration.md
  - Theory:
    - Core Concepts: theory/core-concepts.md
    - Newton's Law of Least Constraint: theory/newton-least-constraint.md
    - Constraints Formulation: theory/constraints.md
    - Non-Linear System of Equations: theory/newton-least-constraint.md
    - Linearization and Solving Linear System: theory/non-linear-system.md
  - Implementation:
    - Engine Overview: implementation/engine.md
    - Configurable Parameters: implementation/parameters.md
    - Logging System: implementation/logging.md
  - Code Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
  
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: red
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
