# @package engine
_target_: axion.MuJoCoEngineConfig
separate_worlds: null
njmax: 200
nconmax: 100
iterations: 100
ls_iterations: 100
solver: "newton"
integrator: "implicitfast"
cone: "elliptic"
impratio: 1.0
use_mujoco_cpu: False
disable_contacts: False
default_actuator_gear: null
actuator_gears: null
update_data_interval: 1
save_to_mjcf: null
ls_parallel: False
use_mujoco_contacts: false
