# @package engine
_target_: axion.XPBDEngineConfig
iterations: 20
soft_body_relaxation: 0.9
soft_contact_relaxation: 0.8
joint_linear_relaxation: 0.7
joint_angular_relaxation: 0.4
rigid_contact_relaxation: 0.7
joint_linear_compliance: 0.00001
joint_angular_compliance: 0.00001
rigid_contact_con_weighting: true
angular_damping: 0.0
enable_restitution: true
