# @package rendering
_target_: axion.RenderingConfig
vis_type: "gl"
target_fps: 20
usd_file: null
# Optional: GL viewer spawn location and initial camera (uncomment to override)
world_offsets: [0.0, 0.0, 0.0]   # where the scene is placed (default: [20, 20, 0])
camera_pos: [1.5, 9.0, 3.5]     # initial camera position (x, y, z)
camera_pitch: 0.0                # degrees
camera_yaw: -90.0               # degrees
