# @package logging
_target_: axion.LoggingConfig
enable_timing: false
enable_hdf5_logging: true 

# Timing options
time_newton_iteration: true
time_linearization: true
time_linear_solve: true
time_linesearch: true

# HDF5 logging options
log_dynamics_state: true
log_linear_system_data: true

log_joint_constraint_data: true
log_contact_constraint_data: true
log_friction_constraint_data: true

log_residual_norm_landscape: true
pca_grid_res: 100
pca_plot_range_scale: 3.0

hdf5_log_file: "${project_name}.h5"

