env:
  env_name: Pendulum
  num_envs: 512
  utils_provider_cfg:
    name: TransformerNeuralModelUtilsProvider
    states_frame: body
    anchor_frame_step: every
    states_embedding_type: identical
    state_prediction_type: relative
    lambda_prediction_type: relative
    prediction_quantity_type: full_state
    num_states_history: 10

algorithm:
  name: LambdaClassificationTrainer
  use_energy_loss: false
  num_epochs: 20
  num_iters_per_epoch: -1
  sample_sequence_length: 10
  batch_size: 1024
  num_valid_batches: 256
  truncate_grad: true
  grad_norm: 1.0
  eval_interval: 0
  loss:
    classification_loss_type: bce_logits
    classification_label_key: lambda_activity
    require_dataset_labels: true
    classification_threshold: 1.0e-3
    classification_prob_threshold: 0.5
    positive_class_weight: 1.0
    classification_eps: 1.0e-8

  optimizer:
    name: adamw
    lr_start: 5e-3
    lr_end: 1e-4
    lr_schedule: cosine
    weight_decay: 8e-4

  dataset:
    train_dataset_path: [src/axion/neural_solver/datasets/Pendulum/pendulumLambdasValid500klen400envs250seed1WithActivityLabels_train.hdf5]
    valid_datasets:
      valid: src/axion/neural_solver/datasets/Pendulum/pendulumLambdasValid500klen400envs250seed1WithActivityLabels_val.hdf5
    max_capacity: 100000000
    num_data_workers: 4

  eval:
    mode: dataset
    rollout_horizon: 10
    num_rollouts: 20000
    dataset_path: src/axion/neural_solver/datasets/Pendulum/pendulumLambdasValid500klen400envs250seed1WithActivityLabels_val.hdf5
    passive: true

inputs:
  low_dim: [
    states_embedding,
    contact_normals,
    contact_points_1,
    contact_depths,
    gravity_dir
  ]

network:
  model_impl: lambda_classification
  normalize_input: true
  normalize_output: false
  enable_state_head: false
  enable_lambda_head: true

  encoder:
    low_dim:
      layer_sizes: []
      activation: relu
      layernorm: false

  transformer:
    block_size: 16
    n_layer: 6       # number of transformer blocks
    n_head: 12        # num transformer heads
    n_embd: 192       # size of input embedding
    dropout: 0.0      # for pretraining 0 is good, for finetuning try 0.1+
    bias: false       # do we use bias inside LayerNorm and Linear layers?

  lambda_model:
    mlp:
      layer_sizes: [64]
      activation: relu
      layernorm: false