# --- Constants remain the same ---
JOINT_CONSTRAINT_STABILIZATION = 0.01
CONTACT_CONSTRAINT_STABILIZATION = 0.1
CONTACT_FB_ALPHA = 0.25
CONTACT_FB_BETA = 0.25
FRICTION_FB_ALPHA = 0.25
FRICTION_FB_BETA = 0.25

MATRIXFREE_SYSTEM = True
