# @package logging
_target_: axion.LoggingConfig
enable_timing: false
enable_hdf5_logging: true
enable_dataset_logging: false
enable_adjoint_logging: true
hdf5_log_file: "data/logs/${project_name}_forward.h5"
adjoint_log_file: "data/logs/${project_name}_grad.h5"
max_simulation_steps: 300
