defaults:
  - simulation: uphill
  - rendering: gl
  - execution: cuda_graph
  - logging: disabled
  - engine: axion
  - _self_

project_name: ${hydra:job.name}

engine.joint_compliance: 5e-6
engine.max_contacts_per_world: 256
