# @package engine
_target_: axion.EngineConfig
newton_iters: 6
linear_iters: 4
linesearch_steps: 2
joint_stabilization_factor: 0.01
contact_stabilization_factor: 0.1
contact_compliance: 1e-4
friction_compliance: 1e-6
contact_fb_alpha: 0.25
contact_fb_beta: 0.25
friction_fb_alpha: 0.25
friction_fb_beta: 0.25
matrixfree_representation: True
