# @package engine
_target_: axion.MuJoCoEngineConfig
separate_worlds: null
njmax: 100
nconmax: 10
iterations: 20
ls_iterations: 10
solver: "newton"
integrator: "implicitfast"
cone: "elliptic"
impratio: 1.0
use_mujoco_cpu: False
disable_contacts: False
default_actuator_gear: null
actuator_gears: null
update_data_interval: 1
save_to_mjcf: null
ls_parallel: False
use_mujoco_contacts: True
joint_solimp_limit: null
