# @package engine
_target_: axion.MuJoCoEngineConfig
separate_worlds: null
njmax: 50
ncon_per_world: null
iterations: 20
ls_iterations: 10
solver: "cg"
integrator: "euler"
cone: "pyramidal"
impratio: 1.0
use_mujoco_cpu: False
disable_contacts: False
default_actuator_gear: null
actuator_gears: null
update_data_interval: 1
save_to_mjcf: null
contact_stiffness_time_const: 0.02
ls_parallel: False
use_mujoco_contacts: True
joint_solref_limit: null
joint_solimp_limit: null